import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const repoRoot = process.cwd();
const mcpDir = path.join(repoRoot, "tools", "viaverse-docs-mcp");

function log(message) {
  console.log(`[viaverse:bootstrap] ${message}`);
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFileIfChanged(filePath, content) {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
  if (current !== content) {
    ensureDir(path.dirname(filePath));
    fs.writeFileSync(filePath, content, "utf8");
    log(`wrote ${path.relative(repoRoot, filePath)}`);
  }
}

function run(command, args, cwd = repoRoot, env = {}) {
  log(`${command} ${args.join(" ")}`);
  const result = spawnSync(command, args, {
    cwd,
    env: { ...process.env, ...env },
    stdio: "inherit",
    shell: process.platform === "win32"
  });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

const envLocal = `# Generated by npm run viaverse:bootstrap
# Local-only. Do not commit real secrets.

VIAVERSE_ENV=local
VIAVERSE_REPO_ROOT=${repoRoot.replaceAll("\\", "\\\\")}

# Stable local ports
VIAVERSE_BACKEND_PORT=8090
VIAVERSE_LANDING_WEB_PORT=3000
VIAVERSE_ADMIN_WEB_PORT=3001
VIAVERSE_BUSINESS_WEB_PORT=3002
VIAVERSE_POSTGRES_PORT=5432
VIAVERSE_REDIS_PORT=6379
VIAVERSE_KAFKA_PORT=9092
VIAVERSE_OPENSEARCH_PORT=9200
VIAVERSE_MAILPIT_SMTP_PORT=1025
VIAVERSE_MAILPIT_WEB_PORT=8025
VIAVERSE_MCP_INSPECTOR_PORT=6274

SEAWEEDFS_MASTER_PORT=9333
SEAWEEDFS_VOLUME_PORT=8080
SEAWEEDFS_FILER_PORT=8888
SEAWEEDFS_S3_PORT=8333

OBJECT_STORAGE_PROVIDER=seaweedfs
OBJECT_STORAGE_ENDPOINT=http://localhost:8333
OBJECT_STORAGE_REGION=local
OBJECT_STORAGE_ACCESS_KEY=viaverse
OBJECT_STORAGE_SECRET_KEY=viaverse-local-secret
OBJECT_STORAGE_BUCKET_MEDIA=viaverse-media-local
OBJECT_STORAGE_PATH_STYLE_ACCESS=true

# Stable local-only development keys.
# Never reuse in staging/production.
VIAVERSE_DEV_JWT_SECRET=viaverse-local-dev-jwt-secret-change-before-prod-64-characters-minimum
VIAVERSE_DEV_INTERNAL_TOKEN=viaverse-local-dev-internal-token-change-before-prod
`;

writeFileIfChanged(path.join(repoRoot, ".env.local"), envLocal);

const codexConfig = `[mcp_servers.viaverse-docs]
enabled = true
command = "node"
args = ["${path.join(repoRoot, "tools", "viaverse-docs-mcp", "dist", "index.js").replaceAll("\\", "\\\\")}"]

[mcp_servers.viaverse-docs.env]
VIAVERSE_REPO_ROOT = "${repoRoot.replaceAll("\\", "\\\\")}"
`;

writeFileIfChanged(path.join(repoRoot, ".codex", "config.toml"), codexConfig);

if (!fs.existsSync(path.join(mcpDir, "package.json"))) {
  console.error(`Missing MCP package.json at ${mcpDir}`);
  process.exit(1);
}

run("npm", ["install"], mcpDir);
run("npm", ["run", "build"], mcpDir, { VIAVERSE_REPO_ROOT: repoRoot });
run("npm", ["run", "docs:index"], mcpDir, { VIAVERSE_REPO_ROOT: repoRoot });
run("npm", ["run", "docs:check"], mcpDir, { VIAVERSE_REPO_ROOT: repoRoot });
run("npm", ["run", "smoke"], mcpDir, { VIAVERSE_REPO_ROOT: repoRoot });

log("done");
log("Codex config generated at .codex/config.toml");
log("Local dev env generated at .env.local");
log("Core infra can be started with ./scripts/dev/start-core-infra.ps1");
