@startuml
title Viaverse Master Program State
[*] --> IDEA
IDEA --> FOUNDATION_READY
FOUNDATION_READY --> ALPHA_VERTICAL_SLICE
ALPHA_VERTICAL_SLICE --> BETA_MARKETPLACE_READY
BETA_MARKETPLACE_READY --> PAYMENT_TRUST_PILOT
PAYMENT_TRUST_PILOT --> BUSINESS_LAUNCH_READY
BUSINESS_LAUNCH_READY --> PUBLIC_TR_LAUNCHED
PUBLIC_TR_LAUNCHED --> SCALE_READY
SCALE_READY --> GLOBAL_READY
GLOBAL_READY --> CONTINUOUS_EVOLUTION
@enduml
